"""stores table

Revision ID: 29e283123c41
Revises: 
Create Date: 2018-02-16 13:56:49.395688

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2 as ga


# revision identifiers, used by Alembic.
revision = '29e283123c41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoneFormatted', sa.String(length=14), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('crossStreet', sa.String(length=64), nullable=True),
    sa.Column('postalCode', sa.String(length=5), nullable=True),
    sa.Column('state', sa.String(length=4), nullable=True),
    sa.Column('geom', ga.types.Geometry(geometry_type='POINT', srid=0), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    # ### end Alembic commands ###
